AlphaScheduler:
  begin_epoch: 10
  max_epoch: 60
  max_value: 0.00015
  min_value: 0.0
Arch:
  input_dim: 1
  name: enet
  num_classes: 2
Data:
  labeled_data_ratio: 0.1
  seed: 1
  unlabeled_data_ratio: 0.9
DataLoader:
  labeled_batch_size: 4
  num_workers: 0
  shuffle: true
  unlabeled_batch_size: 6
  val_batch_size: 6
Dataset: spleen
Dice_config:
  p: 2
  smooth: 1e-15
Optim:
  lr: 0.0001
  name: RAdam
Pacevalue:
  begin_epoch: 5
  max_epoch: 50
  max_value: 1
  min_value: 0.05
RegScheduler:
  begin_epoch: 5
  max_epoch: 50
  max_value: 4
RegScheduler1:
  begin_epoch: 5
  max_epoch: 50
  max_value: 0.5
Scheduler:
  T_max: 90
  name: CosineAnnealingLR
  warmup:
    multiplier: 300
    total_epoch: 10
StartTraining:
  entropy_min: false
  train_jsd: false
Trainer:
  checkpoint_path: runs
  device: cpu
  max_epoch: 100
  name: CoMTSelf
  num_batches: 200
  save_dir: tmp
cons_term: MSE
deepclustering_hash: null
multimodal_hash: !!python/name:builtins.hash ''
num_models: 6
seed: 123
supvised_term: cross_entropy
usetransform: true
